Documentation/Specs/Myget_symbol_server_extensions.md, Documentation/Specs/Package_Based_Symbol_Server.md, Documentation/Specs/Simple_Symbol_Query_Protocol.md
There are known changes based on feedback that are still to come,
but this should get us a baseline.
=> Initial version of publish/download specs

docs/specs/Myget_symbol_server_extensions.md, docs/specs/Package_Based_Symbol_Server.md, docs/specs/Simple_Symbol_Query_Protocol.md
The samples are now out of date, I'll update them seperately
=> Updates the docs from Scott Kupec feedback

src/Microsoft.SymbolStore.Client.Tests/Microsoft.SymbolStore.Client.UnitTests.csproj
VS insistently wants to change this project every time I open the solution.
I had been repeatedly undoing it, but its easier to let VS make its desired edit
than to keep undoing it.
=> Update unit test project

src/EmbedIndex/ELFBuildIdIndexer.cs, src/EmbedIndex/Program.cs
1) It now accepts directory arguments to handle all the packages inside as a batch
2) It warns of ELF files that are missing build ids
3) It now properly indexes .so files
=> EmbedIndex improvements

src/FileFormats.ELF/ELFCoreFile.cs
=> updating ELFCoreFile to prefilter /dev/zero filetable entries

src/FileFormats.Minidump.Tests/Tests.cs, src/FileFormats.Minidump/Minidump.cs, src/FileFormats.Minidump/MinidumpLoadedImage.cs, src/FileFormats.Minidump/MinidumpStructures.cs, src/FileFormats.PE/PEFile.cs, src/FileFormats.PE/PEStructures.cs
Added a few useful minidump properties.
=> Add additional minidump properties

src/EmbedIndex/Program.cs
This shows two possible approaches for adding symbol catalog indexing to EmbedIndex:
1. Add either *.cat or a particular catalog filename or path to the SHA-1 indexer.
2. Add a symbol catalog indexer that indexes the catalog separately.
The SHA-1 indexing approach is simple and the code already exists, but I'm not sure it satisfies security requirements.  The symbol catalog indexer uses SHA-256 which should be fine security-wise, and additionally marks a file as a catalog instead of a generic file, which could have some advantages.
I considered a third approach, similar to the symbol files where a more natural ID is used.  The catalog file itself has internal IDs or signatures that we could use as IDs, but I think this opens up new issues:
- The built-in catalog ID is only 16 bytes and as …
=> Add indexing of symbol catalog files.

src/EmbedIndex/ELFBuildIdIndexer.cs, src/EmbedIndex/MachOUuidIndexer.cs, src/EmbedIndex/PDBSignatureAgeIndexer.cs, src/EmbedIndex/PETimestampSizeIndexer.cs, src/EmbedIndex/Program.cs, src/EmbedIndex/SHA1Indexer.cs, src/EmbedIndex/Utility.cs
- also simplify/unify how we calculate hashes.
=> Update to use one-catalog-per-nupkg mode.

build.sh, src/Microsoft.SymbolStore/KeyGenerators/KeyGenerator.cs, src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs, test.sh
Add build and test scripts for Linux.
=> Fix tests on Linux

eng/SignToolData.json, global.json, src/dotnet-symbol/README.md, src/dotnet-symbol/dotnet-symbol.csproj
Update dotnet-symbol README.md.
=> Build with 2.1.300-rc1-008673.

eng/SignToolData.json, eng/Versions.props
=> Update to signtool with verification disabled.

eng/Versions.props, src/dotnet-symbol/Program.cs, src/dotnet-symbol/Properties/Resources.Designer.cs, src/dotnet-symbol/Properties/Resources.resx
1.0.0-beta2-63127-01
Fixed minor typo in help.
=> Update to official signtool version.

src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs, src/Microsoft.SymbolStore/KeyGenerators/FileKeyGenerator.cs, src/Microsoft.SymbolStore/SymbolStores/CacheSymbolStore.cs, src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs, src/Microsoft.SymbolStore/SymbolStores/SymwebSymbolStore.cs
Also fixed a case for the download tools to display an error if the symbol file can't be found.
=> Change some Warnings to Verbose tracing.

eng/Versions.props, global.json
Update dotnet cli version to 2.1.402
=> Update System.Reflection.Metadata version to match symreader-converter

Directory.Build.props
=> Set RepositoryUrl/ProjectUrl to github repo.

src/Microsoft.FileFormats/PE/PEFile.cs, src/Microsoft.FileFormats/PE/PEStructures.cs, src/Microsoft.SymbolStore/ChecksumValidator.cs, src/Microsoft.SymbolStore/InvalidChecksumException.cs, src/Microsoft.SymbolStore/KeyGenerators/KeyGenerator.cs, src/Microsoft.SymbolStore/KeyGenerators/PDBFileKeyGenerator.cs, src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs, src/Microsoft.SymbolStore/KeyGenerators/PortablePDBFileKeyGenerator.cs, src/Microsoft.SymbolStore/SymbolStoreKey.cs, src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs, src/Microsoft.SymbolStore/SymbolStores/SymbolStore.cs
=> Add SymbolChecksum header to HttpRequest

azure-pipelines.yml
Convert to using stages for validation, publish packages and symbols.
=> Add staging/SDL validation

Directory.Build.targets, azure-pipelines.yml
Fix SourceLink validation failures.
Add back the PR merge build trigger
Add back setting DotNetPublishUsingPipelines
=> Minor eng cleanup

src/Microsoft.FileFormats/PDB/PDBFile.cs, src/Microsoft.SymbolStore/KeyGenerators/PDBFileKeyGenerator.cs
Issue: https://github.com/dotnet/arcade/issues/4763
=> Skip PDBs with empty DbiStreams

src/dotnet-symbol/Properties/Resources.resx
Was just using the tool and noticed a minor discrepancy in actual usage vs. help/display.
=> Minor typo in usage docs.

SymStore.sln, src/Microsoft.FileFormats/ELF/ELFFile.cs, src/Microsoft.FileFormats/ELF/ELFProgramHeader.cs, src/Microsoft.FileFormats/MachO/MachOStructures.cs, src/dotnet-symbol/Program.cs, src/dotnet-symbol/Properties/Resources.resx
--diag displays info about the ELF modules within the core dump.
=> Add --verify ELF core dump option to SymClient.

src/Microsoft.SymbolStore.UnitTests/SymbolStoreTests.cs, src/SymClient/Program.cs, src/SymClient/README.md, src/dotnet-symbol/Program.cs, src/dotnet-symbol/Properties/Resources.Designer.cs, src/dotnet-symbol/Properties/Resources.resx, src/dotnet-symbol/README.md
Issue: https://github.com/dotnet/symstore/issues/358
=> Use https for server URLs

eng/Version.Details.xml, eng/common/build.sh, eng/common/cross/build-rootfs.sh, eng/common/sdl/sdl.ps1, eng/common/templates/job/execute-sdl.yml, eng/common/templates/post-build/post-build.yml, eng/common/templates/steps/execute-codeql.yml, eng/common/templates/steps/execute-sdl.yml, global.json
This should fix the remaining CG warnings.
=> Move arcade to bar build ID: 143014

eng/Versions.props
https://dev.azure.com/dnceng/internal/_build/results?buildId=2017341&view=logs&j=d6d0747d-862c-5953-c201-f4e1a93f2cef&t=2b37f9a2-981d-57e0-a628-adc244ace975&l=17
https://dev.azure.com/dnceng/internal/_build/results?buildId=2017341&view=logs&j=d6d0747d-862c-5953-c201-f4e1a93f2cef&t=2b37f9a2-981d-57e0-a628-adc244ace975&l=23
=> Fix Secure Supply Chain Analysis failure
