dotnet/symstore

- docs/specs/README.md
- docs/specs/SSQP_CLR_Private_Key_Conventions.md
- docs/specs/SSQP_Key_Conventions.md
- docs/specs/Simple_Symbol_Query_Protocol.md
Add docs describing clientKey formats
Add a README to index all the docs
Clarify handling of the '/' character inside SSQP client keys when encoded in URIs and made other minor updates
> SSQP spec updates

- SymStore.sln
- SymStore_dotnet.sln
- src/DownloadDumpFiles/DownloadDumpFiles.xproj
- src/EmbedIndex/EmbedIndex.xproj
- src/FileFormats.ELF.Tests/FileFormats.ELF.Tests.xproj
- src/FileFormats.ELF.Tests/project.json
- src/FileFormats.ELF/FileFormats.ELF.xproj
- src/FileFormats.MachO.Tests/FileFormats.MachO.Tests.xproj
- src/FileFormats.MachO.Tests/project.json
- src/FileFormats.MachO/FileFormats.MachO.xproj
- src/FileFormats.PDB.Tests/FileFormats.PDB.Tests.xproj
- src/FileFormats.PDB.Tests/project.json
- src/FileFormats.PDB/FileFormats.PDB.xproj
- src/FileFormats.PE.Tests/FileFormats.PE.Tests.xproj
- src/FileFormats.PE.Tests/project.json
- src/FileFormats.PE/FileFormats.PE.xproj
- src/FileFormats.Tests/FileFormats.Tests.xproj
- src/FileFormats.Tests/project.json
- src/FileFormats/FileFormats.xproj
The build system in this repo has been problematic to work with ; ) I made SymStore_dotnet.sln as an alternate option that is more useful for local development right now.
I have tried getting the test projects to run following the pattern of the existing unit tests but I have not been successful. FileFormats needs a netstandard 1.5 dependency to build and then the test projects need the same dependency. Once I do that I can no longer follow the existing template exactly, though its unclear if this is really the source of the problem. Ultimately the tests do not show up in the VS test window which is awkward for development. However to get the tests working properly in the xproj based projects I needed to reference netcoreapp instead of netstandard 1.5, and that breaks the build from the …
> Restoring the xproj build

- docs/specs/SSQP_Key_Conventions.md
- src/EmbedIndex/README.md
- src/Microsoft.SymbolStore.Client/StoreQueryBuilder.cs
- src/Microsoft.SymbolStore.Client/SymbolStoreClient.cs
This updates the proposed indexing scheme for portable PDBs to use the MVID plus UInt32.MaxValue as the age. This allows clients that are currently downloading Windows PDBs using symsrv.dll to pretty trivially download portable PDBs.
This also fixes some formatting problems with the .md files in this repo since GitHub now requires a space between the `#` character and the title.
> Update portable PDB indexing scheme and fix formatting

- src/Microsoft.SymbolStore.Client/SymbolStoreClient.cs
The version checks for portable PDB were confusing since they placed the minor version in the upper 16 bits of the 'version' variable. This fixes them.
> Fix portable PDB version check

- src/EmbedIndex/Program.cs
- Key name/blob path tuple was switched around
- Lowercase key name
- Use catalog file name instead of "signature.cat"
> Fix symbol catalog key name.

- docs/specs/SSQP_CLR_Private_Key_Conventions.md
- docs/specs/SSQP_Key_Conventions.md
The cross-platform symbol index format has been changes to better accommodate uploading Linux symbols with only the build id.
> Update docs with new symbol index format

- eng/Versions.props
The symbol client programs (SymClient and dotnet-symbol) and tools like SOS that will reference Microsoft.SymbolStore need to run on 2.0.
> Change System.Reflection.Metadata version back to 1.5

- eng/SignToolData.json
- eng/Versions.props
- global.json
- src/dotnet-symbol/README.md
- src/dotnet-symbol/dotnet-symbol.csproj
Add the properties needed to the dotnet-symbol project to
allow the shims be added to its package.
Update the roslyn repo set to 1.0.0-beta2-63011-08
> Upgrade to dotnet cli 2.1.400-preview-008999

- eng/SignToolData.json
- global.json
- src/dotnet-symbol/dotnet-symbol.csproj
Use the new .NET Core SDK that allows the global tool shims to be put in the output path so they can be properly signed.
> Properly sign the shims for the dotnet-symbol tool.

- src/Microsoft.FileFormats.UnitTests/ELF/Tests.cs
- src/Microsoft.FileFormats.UnitTests/Microsoft.FileFormats.UnitTests.csproj
- src/Microsoft.FileFormats/ELF/ELFFile.cs
FreeBSD .dbg binaries don't have program entries. Use the section entries
to find the build id if so.
https://github.com/dotnet/coreclr/issues/20722
> Fix FreeBSD symbol uploader build failure issue #20722.

- src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/KeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/MachOKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs
- src/Microsoft.SymbolStore/SymbolStores/CacheSymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/SymbolStore.cs
- src/NugetSymbolServer/NugetSymbolServer.csproj
- src/NugetSymbolServer/README.md
- src/NugetSymbolServer/Startup.cs
- src/SymClient/Program.cs
- src/SymClient/SymClient.csproj
- src/dotnet-symbol/Program.cs
- src/dotnet-symbol/dotnet-symbol.csproj
Fixed Path.GetFileName on Windows paths running on Linux.
Fixed NugetSymbolServer project.
Fixed issue #83 and GitHub security alert about Microsoft.AspNetCore.Mvc.
changed dotnet-symbol version to 1.0.1.
Added default cache.
The same location as the SOS symbol server support.
$HOME/.dotnet/symbolcache on xplat.
%USERPROFILE%\.dotnet\symbolcache on Windows.
> Misc fixes and changes.

- src/Microsoft.FileFormats/ELF/ELFFile.cs
- src/Microsoft.SymbolStore/SymbolStores/CacheSymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
- src/dotnet-symbol/dotnet-symbol.csproj
This is an accumulation of dotnet-symbol/symstore fixes.
Fix reads across contiguous adjacent segments. This is the same problem and changes applied to the CLRMD's ELF dump reader recently.
Catch exceptions around create cache directory. This catches and skip caching when the cached file was written previously as superuser.  
Increase the request timeout from 100 seconds (1:40min) to 4 minutes. Issue #87.
> Various dotnet-symbol and symstore fixes

- src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs
- src/dotnet-symbol/dotnet-symbol.csproj
This allows the cross architecture DAC like mscordaccore_x86_arm_4.700.19.28101.dll to be properly uploaded.
Bump dotnet-symbol version to 1.0.4
> Add x86_arm cross DAC/SOS long name support

- src/dotnet-symbol/dotnet-symbol.csproj
- src/dotnet-symbol/runtimeconfig.template.json
Add roll forward config to allow dotnet-symbol to work on 2.2.x and 3.0.x runtimes.
> Update the dotnet-symbol version 1.0.5

- src/Microsoft.SymbolStore/ChecksumValidator.cs
At least on CoreCLR using the symbol store's caching reader, the stream position needs to be restored after checksum validation or it will be omitted from the file. This adds code to do this.
> Restore stream position after checksum validation

- docs/specs/SSQP_Key_Conventions.md
According to the "Key formatting basic rules", the leading zeros should be trimmed.
> [SSQP_Key_Conventions.md] Fix wrong lookup key

- Directory.Build.props
- azure-pipelines.yml
- src/Microsoft.FileFormats/ELF/ELFStructures.cs
- src/Microsoft.FileFormats/Microsoft.FileFormats.csproj
- src/Microsoft.SymbolStore/Microsoft.SymbolStore.csproj
- src/Microsoft.SymbolStore/SymbolStores/CacheSymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/DirectorySymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/SymbolStore.cs
- src/dotnet-symbol/README.md
Fix some symbol publishing problems.
Fix issue #130 by increasing the section/program header count to 30000.
Fix issue #117. Always set the symbol file stream position to 0.
Add Equals, GetHashCode and ToString to the SymbolStore implementations
Fix issue #106.
> Fix various issues

- src/Microsoft.FileFormats/PE/PEStructures.cs
- src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/KeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/MachOKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/PDBFileKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/PortablePDBFileKeyGenerator.cs
- src/dotnet-symbol/Program.cs
- src/dotnet-symbol/Properties/Resources.resx
- src/dotnet-symbol/README.md
Added the --host-only option that downloads the host program usually "dotnet"
or "apphost" renamed to the program/project name for self-contained apps.
> Host program support

- src/Microsoft.FileFormats/MachO/MachOStructures.cs
- src/Microsoft.FileFormats/PE/PEFile.cs
- src/Microsoft.SymbolStore/SymbolStores/CacheSymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/DirectorySymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/SymbolStore.cs
Some macOS dumps were failing becase they had > 1000 commands.
Fixed the cache and directory symbol store IsEqual/GetHashCode functions
to do case-insenstive compare/hashes on Windows.
Add Timeout property on http symbol store for slower networks
> Increase macOS dump command limit

- src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
Treat .debug files as symbols in ELFFileKeyGenerator
Fixes #158
> Treat .debug files as symbols in ELFFileKeyGenerator

- src/Microsoft.SymbolStore/KeyGenerators/KeyGenerator.cs
- src/Microsoft.SymbolStore/SymbolStoreKey.cs
- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
This change moves the URI escaping from where we build the indexes (KeyGenerator.cs) to the http symbol store.  This is so the symbol uploader uses the un-escaped index and the downloader escapes the URI before it gets sent on the network.
The Edge Engineering team uses the SymUploader utility to upload symbol files with blanks and windbg couldn't download them.
> Fix URI double escaping problem

- src/Microsoft.SymbolStore.UnitTests/KeyGeneratorTests.cs
- src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/KeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/MachOKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs
Issue: #181
Add DacDbiKeys key generator flag. Allows SOS to remove some really hacky filtering code.
> Add cross-OS DAC to ELF key generator 

- src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
Due to KeyGenerator check relocatable ELF were rejected as Unknown.
> Treat relocatable ELF file as valid

- src/NugetSymbolServer/Startup.cs
The PlatformAbstractions library is going to be removed from dotnet/runtime.
Contributes to https://github.com/dotnet/runtime/issues/3470
> Remove usage of PlatformAbstractions

- docs/specs/SSQP_Key_Conventions.md
- src/Microsoft.FileFormats/ELF/ELFFile.cs
- src/Microsoft.FileFormats/ELF/ELFNoteHeader.cs
The ELF note headers give name "GNU" and type 3 (NT_GNU_BUILD_ID) for a build ID note, not PRPSINFO.
> Change PrpsInfo to GnuBuildId

- docs/specs/SSQP_Key_Conventions.md
- src/Microsoft.SymbolStore.UnitTests/KeyGeneratorTests.cs
- src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs
Symstore PE index formatting has been slightly incorrect since the beginning. We probably have gotten away with it because the
timestamp for the .NET Core DLLs seems to never have any leading zeros and our servers are case-insensitive. Hopefully because
of this, making this change doesn't break our current upload, download, SOS and other tool usage.
Issue: https://github.com/dotnet/symstore/issues/220
> Fix the PE index formatting

- eng/Versions.props
- src/Microsoft.FileFormats/ELF/ELFFile.cs
Fix ELFFile.IsValid() when missing module header
Update the System.Reflection.Metadata and System.Collections.Immutable versions to match diagnostics repo
> Some misc fixes

- eng/Versions.props
- src/Microsoft.FileFormats/Microsoft.FileFormats.csproj
- src/Microsoft.SymbolStore/Microsoft.SymbolStore.csproj
Upgrading S.R.M to 1.8.7 (from 1.6.0) broke the symuploader net45 framework build. We need to leave the "net45" builds alone as far as dependency versions.
> Revert System.Reflection.Metadata version for net45 framework

- docs/specs/SSQP_Key_Conventions.md
Fixed the example in the documentation to accentuate the casing of lookup keys for PE-files.
> Fixed the example in the documentation

- src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
- src/Microsoft.SymbolStore/SymbolStores/SymwebSymbolStore.cs
- src/dotnet-symbol/Program.cs
- src/dotnet-symbol/Properties/Resources.Designer.cs
- src/dotnet-symbol/Properties/Resources.resx
Make reading section name more bullet proof
Issue: https://github.com/dotnet/symstore/issues/256 and https://github.com/dotnet/symstore/issues/246.
> Add --timeout dotnet-symbol command line option and better "Not Found" error message

- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
It seems like due to the recent change at the storage side, the escaped `index` component of URL is not working anymore.
```sh
$ dotnet symbol --symbols mysinglefilehostapp1 --timeout 20
Downloading from http://msdl.microsoft.com/download/symbols/
ERROR: Not Found: singlefilehost.dbg - 'http://msdl.microsoft.com/download/symbols/_.debug%2Felf-buildid-sym-27997343859af70e0bfc5e50a4d1059b3513a1c4%2F_.debug'
```
http://msdl.microsoft.com/download/symbols/_.debug%2Felf-buildid-sym-27997343859af70e0bfc5e50a4d1059b3513a1c4%2F_.debug is returning 404.
Replacing `%2F` with `/` fixes the issue: http://msdl.microsoft.com/download/symbols/_.debug/elf-buildid-sym-27997343859af70e0bfc5e50a4d1059b3513a1c4/_.debug is valid.
```sh
$ dotnet symbol --symbols mysinglefilehostapp1 --timeout 20
Downloading …
```
> Use EscapeUriString instead of EscapeDataString

- src/Microsoft.FileFormats/MachO/MachCore.cs
- src/Microsoft.FileFormats/MachO/MachOFile.cs
- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
Reworked the symbol lookup code. Needed to fallback to search all symbols if it can find the it in the exported symbols. It always read every symbol name in the old path.
> Fix issue https://github.com/dotnet/symstore/issues/327

- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
Don't mark permanent failures for some socket errors.
> Add retry logic to HttpSymbolStore to help make the diagnostics repo tests more reliable

- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
I hit an issue where the retry logic introduced in https://github.com/dotnet/symstore/pull/336 was not triggering a retry when expected.  In my scenario, the retryable socket error (`SocketError.ConnectionReset`) is wrapped inside an `IOException` so it's never discovered. This PR updates the retry logic to check all of the inner exceptions for any `SocketException`.
Output of a repro of this issue:
```csharp
HttpSymbolStore: System.Threading.pdb retryable False socketError Success 'https://msdl.microsoft.com/download/symbols/system.threading.pdb/0b2084837920461e848e61a94c16d65cFFFFFFFF/system.threading.pdb' System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by …
```
> Update retry logic in HttpSymbolStore to check nested inner exceptions

- azure-pipelines.yml
As a part of https://github.com/dotnet/arcade/issues/10123, we are moving all docker containers to the "latest" tagging schema
> Update docker image to the latest schema

- src/Microsoft.FileFormats/PE/PEFile.cs
Some managed PE's have the version resource only as "neutral" language. Single-file apps and our test debuggees are examples.
> Fix getting version resource on PE files

- src/Microsoft.FileFormats/Pointer.cs
- src/Microsoft.FileFormats/TStruct.cs
Delay getting a Pointer's target type layout until the pointer's target is dereferenced to avoid recursion/stack overflow when creating the layout for types that have a field that a Pointer to itself.
This does change some protected fields in the PointerLayout (_storageLayout, _targetLayout) and Pointer (_targetLayout) classes but I think the chances are very low that some one depends on them.
Added LayoutManager.AddReflectionTypes override with a typeFilter that allows duplicated code to be removed from the DCR.
> Pointer layout changes

- src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
8 byte/64 bit build ids need to be padding to 20 bytes/160 bits according to spec.
> Fix ELF build id key generator padding

- src/Microsoft.FileFormats/ELF/ELFFile.cs
- src/Microsoft.FileFormats/MachO/MachOFile.cs
- src/Microsoft.FileFormats/PDB/PDBFile.cs
- src/Microsoft.FileFormats/PE/PEFile.cs
- src/Microsoft.FileFormats/StreamAddressSpace.cs
Fix issue https://github.com/dotnet/symstore/issues/400 arithmetic overflow reading PDBs with -1 stream sizes.
Fix overflow reading resources from a PE when entry counts are -1.
Make ELFFile, MachOFile, PEFile and PDBFile IDisposable for diagnostics repo changes.
> Fix a couple of arithmetic overflows

- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
This PR adds in a new class SymbolAuthHeader which contains a scheme and parameter that will be passed into AuthenticationHeaderValue's constructor.
This will allow non-"Basic" auth headers such as "Bearer" and etc.
@gregg-miskelly @chuckries
> Add support for non-Basic Auth PAT tokens

- src/Microsoft.FileFormats/ELF/ELFFile.cs
The problem is that the program header NOTE file offset is incorrectly the virtual offset.
This is fixed by falling back to getting the build id from the Section headers when reading the program header NOTE overflows or fails.
> Fix overflow on certain ELF symbol files
